      - name: Deploy via SCP
        run: |
          scp -P $SSH_PORT -r . $SSH_USER@$HOSTINGER_IP:/home/$SSH_USER/public_html/api

      - name: Run Laravel Commands via SSH
        run: |
          ssh -p $SSH_PORT $SSH_USER@$HOSTINGER_IP << 'EOF'
            cd public_html/api
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            exit
          EOF
