name: Deploy Laravel to Hostinger via SSH

on:
  push:
    branches:
      - master  # Change this if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug SSH Variables
        run: |
          echo "SSH_PORT: $SSH_PORT"
          echo "SSH_USER: $SSH_USER"
          echo "HOSTINGER_IP: $HOSTINGER_IP"

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTINGER_IP: ${{ secrets.HOSTINGER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SSH_PORT -H $HOSTINGER_IP >> ~/.ssh/known_hosts

      - name: Deploy Laravel API to Hostinger
        run: |
          ssh -p $SSH_PORT $SSH_USER@$HOSTINGER_IP << 'EOF'
            cd public_html/api
            
            echo "🔄 Resetting Git Repository"
            git reset --hard
            git pull origin master
            
            echo "📦 Installing Dependencies"
            composer install --no-dev --optimize-autoloader
            
            echo "🚀 Running Migrations"
            php artisan migrate --force
            
            echo "🧹 Clearing Caches"
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            echo "✅ Deployment Complete"
            exit
          EOF
